export type Block =
  | { type: 'paragraph'; text: string }
  | { type: 'heading'; text: string }
  | { type: 'callout'; text: string }
  | { type: 'quote'; text: string; attribution?: string }
  | { type: 'list'; items: string[] }

export type FAQ = { question: string; answer: string }

export type Article = {
  slug: string
  title: string
  excerpt: string
  categories: string[]
  gradient: string
  image?: string
  readTime: string
  date: string
  featured: boolean
  faqs: FAQ[]
  relatedSlugs: string[]
  body: Block[]
}

const articles: Article[] = [
  {
    slug: 'heloc-vs-cash-out-refinance',
    title: 'HELOC vs. Cash-Out Refinance: Which Is Right for You?',
    excerpt: 'Both options let you access your home equity — but they work very differently. Here\'s how to choose the right one for your situation.',
    categories: ['HELOC'],
    gradient: 'linear-gradient(135deg, #c4ccaa 0%, #8C9870 100%)',
    image: '/images/resources-1.png',
    readTime: '5 min read',
    date: 'June 10, 2025',
    featured: true,
    relatedSlugs: ['dscr-loans-explained', 'bank-statement-loans', 'jumbo-loan-requirements'],
    faqs: [
      {
        question: 'Can I have both a HELOC and a cash-out refinance?',
        answer: 'Not simultaneously on the same property. However, you could use a cash-out refinance to pay off an existing HELOC, or vice versa, depending on your goals and equity position.',
      },
      {
        question: 'Is HELOC interest tax deductible?',
        answer: 'HELOC interest may be deductible if the funds are used to buy, build, or substantially improve the home securing the loan. Consult a tax professional for guidance specific to your situation.',
      },
      {
        question: 'What credit score do I need for a HELOC?',
        answer: 'Most lenders prefer a credit score of 680 or higher for a HELOC. Requirements vary by lender and loan-to-value ratio.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'If you\'ve built meaningful equity in your home, you have options. Two of the most common ways to access that equity are a Home Equity Line of Credit (HELOC) and a cash-out refinance. Both can be powerful financial tools — but they serve different needs and carry different structures.' },
      { type: 'heading', text: 'What Is a HELOC?' },
      { type: 'paragraph', text: 'A HELOC is a revolving line of credit secured by your home. Similar to a credit card, you draw from it as needed during a set draw period — typically 5 to 10 years — and pay interest only on what you use. After the draw period ends, you repay the principal over a repayment period.' },
      { type: 'callout', text: 'HELOCs are commonly structured with variable interest rates tied to the prime rate, allowing borrowers flexibility during the draw period. For homeowners seeking greater certainty, fixed-rate HELOC options may also be available.' },
      { type: 'heading', text: 'What Is a Cash-Out Refinance?' },
      { type: 'paragraph', text: 'A cash-out refinance replaces your existing mortgage with a new, larger loan. You receive the difference between the new loan amount and your current mortgage balance in cash at closing. Because you\'re starting a new mortgage, you\'ll have a new rate and new terms — which can be advantageous if rates have moved in your favor since your original loan.' },
      { type: 'heading', text: 'Key Differences at a Glance' },
      { type: 'list', items: [
        'A HELOC keeps your existing mortgage intact; a cash-out refinance replaces it.',
        'HELOCs offer flexibility — draw and repay as needed during the draw period.',
        'Cash-out refinances provide a lump sum with fixed repayment from day one.',
        'Closing costs for a cash-out refinance are typically higher.',
      ]},
      { type: 'quote', text: 'The right choice depends on how you plan to use the funds and how long you intend to stay in your home. There\'s no universal answer — only the one that aligns with your goals.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
      { type: 'heading', text: 'Which Is Right for You?' },
      { type: 'paragraph', text: 'If you need funds over time — for ongoing renovations, a business expense, or a flexible reserve — a HELOC\'s draw-and-repay structure is difficult to beat. If you\'re consolidating high-interest debt or need a large lump sum at a predictable rate, a cash-out refinance may provide better long-term savings. Consider your timeline, risk tolerance, and how long you plan to stay in the home before deciding.' },
    ],
  },
  {
    slug: 'dscr-loans-explained',
    title: 'DSCR Loans Explained: Qualifying on Rental Income',
    excerpt: 'Debt Service Coverage Ratio loans let investors qualify based on property income — no personal tax returns required.',
    categories: ['DSCR'],
    gradient: 'linear-gradient(135deg, #b8b0a8 0%, #756C5F 100%)',
    image: '/images/resources-2.png',
    readTime: '6 min read',
    date: 'May 28, 2025',
    featured: true,
    relatedSlugs: ['heloc-vs-cash-out-refinance', 'bank-statement-loans', 'jumbo-loan-requirements'],
    faqs: [
      {
        question: 'What DSCR ratio do lenders typically require?',
        answer: 'Most lenders look for a DSCR of 1.0 or higher, though some allow ratios slightly below 1.0 with compensating factors. A ratio of 1.25 or above is generally considered strong.',
      },
      {
        question: 'Can I use a DSCR loan for a short-term rental property?',
        answer: 'Yes. Many lenders accept short-term rental income for DSCR qualification. Some use a market rent analysis; others use documented short-term rental history. Guidelines vary by lender.',
      },
      {
        question: 'Do I need good credit for a DSCR loan?',
        answer: 'Yes. While DSCR loans don\'t require tax returns, lenders still review credit scores. A score of 680 or higher is typically required, with better pricing available for scores of 720 and above.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'For real estate investors, traditional mortgage qualification can be a meaningful barrier. Tax returns that reflect deductions and business losses rarely tell the full story of an investor\'s financial strength. DSCR loans were designed with exactly that in mind.' },
      { type: 'heading', text: 'How DSCR Is Calculated' },
      { type: 'paragraph', text: 'DSCR stands for Debt Service Coverage Ratio. It measures whether a property\'s income is sufficient to cover its debt obligations. The formula is straightforward: divide the property\'s gross rental income by its total monthly debt service — principal, interest, taxes, insurance, and HOA dues if applicable.' },
      { type: 'callout', text: 'DSCR = Gross Rental Income ÷ Total Monthly Debt Service. A ratio of 1.0 means the property breaks even. Above 1.0 means it generates positive cash flow relative to its obligations.' },
      { type: 'heading', text: 'Who Benefits Most from DSCR Financing?' },
      { type: 'list', items: [
        'Investors with multiple properties and complex tax returns',
        'Self-employed borrowers whose income is difficult to document through traditional channels',
        'Portfolio builders looking to scale without DTI constraints',
        'Foreign nationals investing in U.S. real estate',
        'Borrowers who want to keep business and personal finances clearly separated',
      ]},
      { type: 'heading', text: 'What Lenders Evaluate' },
      { type: 'paragraph', text: 'While personal income documentation is not required, lenders do review credit score, property type, loan-to-value ratio, and a market rent analysis — typically provided by a licensed appraiser. Most programs require the property to be non-owner-occupied. Eligible property types generally include single-family residences, 2–4 unit properties, condos, and in some cases 5+ unit multifamily.' },
      { type: 'quote', text: 'DSCR financing has become one of the most powerful tools for real estate investors. It allows the property to speak for itself — without the noise of a complex tax return.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'bank-statement-loans',
    title: 'Bank Statement Loans for Self-Employed Borrowers',
    excerpt: 'If your tax returns don\'t reflect your actual cash flow, a bank statement loan may be the solution you\'ve been looking for.',
    categories: ['Self Employed'],
    gradient: 'linear-gradient(135deg, #c8d4cc 0%, #6a8a86 100%)',
    image: '/images/resources-3.png',
    readTime: '5 min read',
    date: 'May 14, 2025',
    featured: true,
    relatedSlugs: ['dscr-loans-explained', 'heloc-vs-cash-out-refinance', 'jumbo-loan-requirements'],
    faqs: [
      {
        question: 'How many months of bank statements are required?',
        answer: 'Most lenders require either 12 or 24 months of bank statements. Using 24 months often provides a more complete income picture and may improve your qualifying amount.',
      },
      {
        question: 'Can I use business bank statements instead of personal?',
        answer: 'Yes. Many lenders accept business bank statements. In that case, an expense ratio is typically applied to estimate net income from the deposits shown — commonly 50%, though it varies by lender and industry.',
      },
      {
        question: 'What is the difference between a bank statement loan and a P&L loan?',
        answer: 'A bank statement loan uses your actual deposit history to determine income. A P&L loan uses a profit and loss statement prepared by a licensed CPA. Both are alternatives to traditional tax-return-based qualification.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'Self-employment offers independence — but it can complicate mortgage qualification. When you deduct legitimate business expenses, your taxable income often appears much lower than your actual cash flow. Bank statement loans were created to bridge that gap.' },
      { type: 'heading', text: 'How Bank Statement Loans Work' },
      { type: 'paragraph', text: 'Instead of W-2s or tax returns, the lender analyzes 12 or 24 months of your bank statements to establish an average monthly income. Deposits are reviewed, large non-recurring transfers are typically excluded, and a consistent income picture is constructed from what actually moved through your account.' },
      { type: 'callout', text: 'Business owners using business accounts should note that lenders typically apply an expense ratio — often 50% — to account for overhead before calculating qualifying income. Using personal statements avoids this adjustment.' },
      { type: 'heading', text: 'Who Qualifies?' },
      { type: 'list', items: [
        'Freelancers and independent contractors',
        'Business owners and entrepreneurs',
        'Consultants and self-employed professionals',
        'Gig economy workers with variable income',
        'Real estate professionals and commission-based earners',
      ]},
      { type: 'heading', text: 'P&L and VOE as Alternatives' },
      { type: 'paragraph', text: 'If bank statements don\'t clearly present your income, a CPA-prepared Profit & Loss statement may be used instead. Some programs also accept a Verification of Employment letter for W-2 employees receiving significant supplemental income. These options give self-employed borrowers meaningful flexibility without requiring a conventional paper trail.' },
      { type: 'quote', text: 'Many of my clients have excellent cash flow and financial discipline — their tax returns simply don\'t reflect it. That\'s exactly why these programs exist.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'buying-before-selling',
    title: 'How to Buy a Home Before Selling Your Current One',
    excerpt: 'You don\'t have to sell before you can buy. Bridge financing and strategic planning can make the transition seamless in any market.',
    categories: ['Bridge Loan', 'Hard Money', 'Conventional'],
    gradient: 'linear-gradient(135deg, #d4c8be 0%, #C4A49E 100%)',
    image: '/images/resources-4.png',
    readTime: '7 min read',
    date: 'April 30, 2025',
    featured: true,
    relatedSlugs: ['heloc-vs-cash-out-refinance', 'jumbo-loan-requirements', 'fha-vs-conventional'],
    faqs: [
      {
        question: 'What is a bridge loan?',
        answer: 'A bridge loan is short-term financing that allows you to access equity from your current home to fund the purchase of a new one, before your existing home sells.',
      },
      {
        question: 'How long does a bridge loan last?',
        answer: 'Most bridge loans have terms of 6 to 12 months. They\'re designed to be repaid when your current home sells.',
      },
      {
        question: 'Is bridge financing expensive?',
        answer: 'Bridge loans carry higher interest rates than conventional financing. However, that cost must be weighed against the advantage of making a competitive, non-contingent offer in a market where timing matters.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'In a competitive market, the ability to make a clean, non-contingent offer can be the difference between securing the right home and losing it to another buyer. But most homeowners don\'t have the liquidity to fund a new purchase before their current property sells. Bridge financing exists precisely for this situation.' },
      { type: 'heading', text: 'What Is a Bridge Loan?' },
      { type: 'paragraph', text: 'A bridge loan is short-term financing that uses the equity in your current home as collateral to fund the purchase of your next home. It bridges the gap between your sale and your purchase, giving you the capital to act without waiting.' },
      { type: 'heading', text: 'Strategies for Buying Before Selling' },
      { type: 'list', items: [
        'Use a bridge loan to tap existing equity and fund your down payment',
        'Request a delayed closing on your new purchase to allow time for your sale',
        'Leverage a HELOC on your current home if available credit exists',
        'Negotiate a rent-back agreement to stay in your current home post-sale',
        'Work with your lender to qualify for both mortgages simultaneously if income supports it',
      ]},
      { type: 'callout', text: 'A non-contingent offer is significantly more competitive in most markets. Bridge financing can be the difference between being a serious contender and losing a property you\'ve already identified as the right one.' },
      { type: 'heading', text: 'What to Consider Before Proceeding' },
      { type: 'paragraph', text: 'Bridge loans carry higher rates and fees than conventional financing. Before proceeding, consider your carrying costs, how quickly homes are selling in your current market, and whether your lender can qualify you for both mortgages simultaneously without the bridge. In strong markets, homes often sell quickly — which reduces the time you\'d carry two properties.' },
      { type: 'quote', text: 'The fear of being stuck with two mortgages often stops buyers from acting on the right opportunity. With the right plan, that window is usually shorter than people expect.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'reverse-mortgage-myths',
    title: 'Reverse Mortgage Myths — and the Reality Behind Them',
    excerpt: 'Misconceptions about reverse mortgages are widespread. Here\'s an honest look at how they actually work and who they\'re designed for.',
    categories: ['Reverse'],
    gradient: 'linear-gradient(135deg, #c4c0ba 0%, #8a8478 100%)',
    image: '/images/resources-5.png',
    readTime: '6 min read',
    date: 'April 15, 2025',
    featured: false,
    relatedSlugs: ['heloc-vs-cash-out-refinance', 'buying-before-selling', 'fha-vs-conventional'],
    faqs: [
      {
        question: 'Does the bank own my home with a reverse mortgage?',
        answer: 'No. You retain ownership of your home throughout the life of the loan. The lender holds a lien, as with any mortgage, but you remain on title.',
      },
      {
        question: 'What happens to the loan when I pass away?',
        answer: 'Your heirs can repay the loan balance — typically by selling the home or refinancing — and keep any remaining equity. They are not personally liable for amounts that exceed the home\'s value.',
      },
      {
        question: 'Can I still leave my home to my children?',
        answer: 'Yes. If your heirs choose to repay the loan balance, they can retain the home. The reverse mortgage does not prevent inheritance — it simply means the balance must be settled first.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'Reverse mortgages — formally known as Home Equity Conversion Mortgages (HECMs) — have been misunderstood for decades. For the right borrower, they can be a transformative retirement planning tool. Understanding the reality is the first step toward making an informed decision.' },
      { type: 'heading', text: 'Myth 1: The Bank Takes Your Home' },
      { type: 'paragraph', text: 'This is the most pervasive misconception. With a reverse mortgage, you retain full ownership of your home. The lender places a lien on the property, as with any mortgage, but you remain on title. The loan becomes due when you sell, move out permanently, or pass away — not before.' },
      { type: 'heading', text: 'Myth 2: You Can Owe More Than Your Home Is Worth' },
      { type: 'paragraph', text: 'HECMs are non-recourse loans. If the loan balance ever exceeds your home\'s value, neither you nor your heirs are responsible for the difference. The FHA insurance fund covers that shortfall — a meaningful consumer protection built into the program.' },
      { type: 'callout', text: 'HECMs are insured by the FHA and require independent counseling before closing. These protections were built specifically to ensure borrowers understand what they\'re signing.' },
      { type: 'heading', text: 'Who Are Reverse Mortgages Right For?' },
      { type: 'list', items: [
        'Homeowners age 62 and older with substantial equity',
        'Those who plan to remain in their home long-term',
        'Retirees looking to supplement fixed income without selling assets',
        'Borrowers seeking to eliminate a required monthly mortgage payment',
        'Those who want to fund healthcare or improvements without depleting savings',
      ]},
      { type: 'quote', text: 'A reverse mortgage isn\'t a last resort — it\'s a planning tool. Used strategically, it can meaningfully extend the longevity of a retirement portfolio.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'fha-vs-conventional',
    title: 'FHA vs. Conventional: Which Loan Is Right for You?',
    excerpt: 'FHA and conventional loans each have distinct advantages. Your credit profile, down payment, and long-term goals determine which fits best.',
    categories: ['FHA', 'Conventional'],
    gradient: 'linear-gradient(135deg, #c4ccaa 0%, #A8B08E 100%)',
    image: '/images/resources-6.png',
    readTime: '5 min read',
    date: 'March 30, 2025',
    featured: false,
    relatedSlugs: ['va-loan-benefits', 'jumbo-loan-requirements', 'buying-before-selling'],
    faqs: [
      {
        question: 'What is the minimum down payment for an FHA loan?',
        answer: 'FHA loans allow a down payment as low as 3.5% for borrowers with a credit score of 580 or higher. Borrowers with scores between 500–579 may qualify with a 10% down payment.',
      },
      {
        question: 'Can I use an FHA loan for an investment property?',
        answer: 'No. FHA loans are for primary residences only. For investment properties, consider conventional, DSCR, or other non-QM programs.',
      },
      {
        question: 'When can I remove mortgage insurance on a conventional loan?',
        answer: 'Conventional PMI can be removed once you reach 20% equity through appreciation or principal paydown. FHA MIP, by contrast, typically lasts the life of the loan if your down payment was less than 10%.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'For many homebuyers, the choice between FHA and conventional financing comes down to credit score, down payment, and long-term cost. Neither is universally superior — each serves a distinct borrower profile.' },
      { type: 'heading', text: 'FHA Loans: Greater Accessibility' },
      { type: 'paragraph', text: 'FHA loans are backed by the Federal Housing Administration and designed to broaden homeownership access. They allow credit scores as low as 580 with a 3.5% down payment, and qualifying guidelines are generally more flexible for borrowers with higher debt-to-income ratios or recent credit challenges.' },
      { type: 'heading', text: 'Conventional Loans: More Flexibility Over Time' },
      { type: 'paragraph', text: 'Conventional loans are not government-backed, and they typically require a stronger credit profile. However, they offer significant advantages: no upfront mortgage insurance premium, lower total insurance costs for well-qualified borrowers, and the ability to finance second homes and investment properties.' },
      { type: 'callout', text: 'FHA MIP is required for the life of the loan if your down payment is below 10%. Conventional PMI drops off once you reach 20% equity — an important long-term cost consideration.' },
      { type: 'heading', text: 'Key Comparison Points' },
      { type: 'list', items: [
        'Minimum credit score: FHA 580 (3.5% down) vs. Conventional 620+',
        'Down payment: FHA 3.5% minimum vs. Conventional 3–5% minimum',
        'Mortgage insurance: FHA MIP (life of loan if <10% down) vs. Conventional PMI (removable at 20% equity)',
        'Property types: FHA primary residences only vs. Conventional primary, second home, investment',
        'Upfront MIP: FHA charges 1.75% upfront; conventional has no equivalent',
      ]},
      { type: 'quote', text: 'The right program is the one that gets you into the home you want while minimizing long-term cost. That calculation is different for every borrower.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'va-loan-benefits',
    title: 'VA Loan Benefits: What Every Eligible Borrower Should Know',
    excerpt: 'VA loans offer some of the most favorable terms available in residential lending. Here\'s what eligible service members and veterans should understand.',
    categories: ['VA'],
    gradient: 'linear-gradient(135deg, #bcc8c4 0%, #6a8a86 100%)',
    image: '/images/resources-7.png',
    readTime: '5 min read',
    date: 'March 15, 2025',
    featured: false,
    relatedSlugs: ['fha-vs-conventional', 'jumbo-loan-requirements', 'buying-before-selling'],
    faqs: [
      {
        question: 'Can I use a VA loan more than once?',
        answer: 'Yes. VA loan benefits can be used multiple times, as long as you have remaining entitlement or restore your entitlement after repaying a previous VA loan.',
      },
      {
        question: 'Is there a VA loan limit?',
        answer: 'As of 2020, VA loan limits were eliminated for borrowers with full entitlement. Borrowers with reduced entitlement may still have limits tied to conforming loan amounts in their county.',
      },
      {
        question: 'Do I need a down payment for a VA loan?',
        answer: 'In most cases, eligible borrowers can purchase with no down payment. This is one of the most significant advantages of VA financing and sets it apart from virtually every other loan type.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'The VA loan program was established in 1944 as part of the GI Bill, and it remains one of the most powerful mortgage benefits available to eligible service members, veterans, and surviving spouses. Despite its advantages, VA financing is consistently underutilized — often because borrowers are unaware of what the program truly offers.' },
      { type: 'heading', text: 'No Down Payment Required' },
      { type: 'paragraph', text: 'Perhaps the most significant advantage of a VA loan is the ability to purchase a home with no down payment. This benefit alone can allow a veteran to move from renting to homeownership without years of saving, freeing capital for other financial priorities.' },
      { type: 'heading', text: 'No Private Mortgage Insurance' },
      { type: 'paragraph', text: 'Unlike FHA and conventional loans with less than 20% down, VA loans do not require private mortgage insurance. This can represent hundreds of dollars in monthly savings — compounded over the life of the loan.' },
      { type: 'callout', text: 'VA loans do have a funding fee — a one-time charge that can be financed into the loan. Certain borrowers, including those with service-connected disabilities, may be exempt from this fee entirely.' },
      { type: 'heading', text: 'Additional Benefits Worth Knowing' },
      { type: 'list', items: [
        'Competitive interest rates — often lower than conventional alternatives',
        'No prepayment penalties',
        'Flexible credit and debt-to-income guidelines',
        'Assumable loans — a future buyer can take over your VA loan, which can be valuable in a rising rate environment',
        'No loan limits for borrowers with full entitlement',
      ]},
      { type: 'quote', text: 'The VA loan is one of the most underused benefits available to those who\'ve served. If you\'re eligible and not using it, it\'s worth understanding exactly what you\'re leaving on the table.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'jumbo-loan-requirements',
    title: 'Jumbo Loan Requirements: What to Expect',
    excerpt: 'Jumbo loans exceed conventional lending limits and require a stronger qualifying profile. Here\'s what lenders look for and how to prepare.',
    categories: ['Jumbo'],
    gradient: 'linear-gradient(135deg, #d4c8be 0%, #b0a29a 100%)',
    image: '/images/resources-8.png',
    readTime: '5 min read',
    date: 'February 28, 2025',
    featured: false,
    relatedSlugs: ['fha-vs-conventional', 'bank-statement-loans', 'dscr-loans-explained'],
    faqs: [
      {
        question: 'What is the jumbo loan threshold in 2025?',
        answer: 'In most U.S. counties, jumbo loans begin above $766,550 for a single-family home. High-cost areas have higher conforming limits. Loan amounts above these thresholds require non-conforming financing.',
      },
      {
        question: 'Can I get a jumbo loan with less than 20% down?',
        answer: 'Some jumbo programs allow down payments as low as 10%, though they typically require strong credit and may carry higher rates or require mortgage insurance.',
      },
      {
        question: 'Are jumbo loan rates higher than conforming rates?',
        answer: 'Historically, jumbo rates were higher than conforming rates. In recent years, the gap has narrowed significantly — and jumbo rates are sometimes competitive with or lower than conforming rates, depending on the lender and borrower profile.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'When a loan amount exceeds the conforming limit set by the Federal Housing Finance Agency, it enters jumbo territory. Because these loans cannot be sold to Fannie Mae or Freddie Mac, lenders carry the risk themselves — which typically translates to more rigorous qualification requirements.' },
      { type: 'heading', text: 'Credit Score Requirements' },
      { type: 'paragraph', text: 'Most jumbo lenders require a credit score of at least 700, with many preferring 720 or higher. The higher your score, the more competitive the pricing you\'re likely to receive. Some lenders tier their rates based on specific score bands, so the difference between 719 and 720 can be meaningful.' },
      { type: 'heading', text: 'Down Payment and Reserves' },
      { type: 'paragraph', text: 'While some jumbo programs allow 10–15% down, most lenders prefer 20% or more. Beyond the down payment, jumbo lenders often require substantial cash reserves — typically 6 to 12 months of principal, interest, taxes, and insurance — held in verifiable accounts.' },
      { type: 'callout', text: 'Reserves matter significantly in jumbo underwriting. Having 12 or more months of PITIA in reserve can meaningfully improve your rate, your approval odds, and the overall underwriting experience.' },
      { type: 'heading', text: 'Debt-to-Income Ratio' },
      { type: 'paragraph', text: 'Conforming loan guidelines allow DTI ratios up to 50% in some cases. Jumbo lenders are generally stricter, preferring a DTI of 43% or below. Some will go higher with significant reserves and a well-rounded financial profile.' },
      { type: 'heading', text: 'Documentation' },
      { type: 'paragraph', text: 'Most jumbo programs require full income documentation — two years of tax returns, W-2s, and 30 days of pay stubs for W-2 earners. For high-income self-employed borrowers, some lenders offer jumbo bank statement programs that bypass traditional income documentation requirements.' },
      { type: 'quote', text: 'Jumbo buyers often have complex financial profiles. Taking time to position your application thoughtfully can make a meaningful difference in both approval odds and final pricing.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'what-is-a-hard-money-loan',
    title: 'What Exactly Is a Hard Money Loan?',
    excerpt: 'Hard money loans are equity-based, privately funded, and built for speed. Here\'s when they make sense — and when they don\'t.',
    categories: ['Hard Money'],
    gradient: 'linear-gradient(135deg, #c8bfb4 0%, #8a7d70 100%)',
    image: '/images/resources-9.png',
    readTime: '5 min read',
    date: 'June 10, 2026',
    featured: false,
    relatedSlugs: ['buying-before-selling', 'dscr-loans-explained', 'jumbo-loan-requirements'],
    faqs: [
      {
        question: 'Who provides hard money loans?',
        answer: 'Hard money loans are funded by private lenders, investment funds, or individuals — not traditional banks. Because they operate outside conventional underwriting, they can move quickly and accommodate scenarios that traditional lenders cannot.',
      },
      {
        question: 'What interest rates do hard money loans carry?',
        answer: 'Rates vary widely depending on the lender, loan-to-value, and borrower profile, but hard money loans typically carry higher rates than conventional financing. The tradeoff is speed, flexibility, and access — not cost.',
      },
      {
        question: 'How long can I hold a hard money loan?',
        answer: 'Most hard money loans are short-term, ranging from 6 to 24 months. They are designed as bridge financing — not permanent solutions. Having a defined exit strategy before closing is essential.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'Hard money loans are a category of financing that most borrowers never need to think about — until they do. When a deal moves fast, when a property doesn\'t qualify for conventional financing, or when time matters more than rate, hard money can be the only path forward.' },
      { type: 'paragraph', text: 'The defining characteristic of a hard money loan is that it is asset-based. Rather than qualifying on income, credit history, and debt-to-income ratios the way a traditional mortgage does, hard money lenders focus primarily on the value and equity of the property. Your ability to repay is evaluated, but the underwriting process is shorter and more flexible.' },
      { type: 'heading', text: 'When Hard Money Is Used' },
      { type: 'list', items: [
        'Fix-and-flip investors purchasing a property that requires significant renovation before it qualifies for conventional financing.',
        'Bridge scenarios where a buyer needs to close on a new property before their current home sells.',
        'Time-sensitive purchases — auction properties, foreclosures, or off-market deals where a 30-day close isn\'t possible conventionally.',
        'Properties in poor condition that traditional lenders will not touch.',
        'Borrowers who need short-term financing while their long-term loan is being arranged.',
      ]},
      { type: 'heading', text: 'The Role of Exit Strategy' },
      { type: 'paragraph', text: 'A hard money loan is not a destination. It is a bridge. Before committing to this type of financing, every borrower should have a defined and realistic exit strategy: Will you sell the property? Refinance into a conventional or DSCR loan? Pay it off through other liquidity? The answer should be clear before closing, not figured out afterward.' },
      { type: 'callout', text: 'Hard money is a tool, not a last resort. When used intentionally — with a defined purpose, timeline, and exit — it can unlock opportunities that conventional financing simply cannot reach.' },
      { type: 'heading', text: 'When Hard Money May Not Make Sense' },
      { type: 'paragraph', text: 'If you have time, strong documentation, and a property that qualifies conventionally, traditional financing will almost always be less expensive. Hard money carries higher rates and fees by design — the premium is the price of speed and flexibility. It is not the right tool for every situation, and using it unnecessarily adds cost without benefit.' },
      { type: 'heading', text: 'Comparing Hard Money to Traditional Mortgage Financing' },
      { type: 'paragraph', text: 'A conventional mortgage is underwritten based on your income, credit, debt, and the property\'s appraised value. It typically takes 30 to 45 days to close and carries lower rates. Hard money focuses on equity, moves in days to weeks, and carries higher rates in exchange for access and speed. Neither is inherently better — the right tool depends on the situation.' },
      { type: 'quote', text: 'Every hard money deal should start with a clear question: what is the exit? If that answer is uncertain, it\'s worth slowing down before the loan commits you to a timeline.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'foreign-nationals-buying-us-property',
    title: 'Can Foreign Nationals Buy Property in the United States?',
    excerpt: 'Non-U.S. citizens and non-residents may still be able to purchase American real estate. Here\'s how foreign national financing works.',
    categories: ['Foreign National'],
    gradient: 'linear-gradient(135deg, #ccd0c4 0%, #7a8a6e 100%)',
    image: '/images/resources-10.png',
    readTime: '6 min read',
    date: 'June 5, 2026',
    featured: false,
    relatedSlugs: ['jumbo-loan-requirements', 'dscr-loans-explained', 'bank-statement-loans'],
    faqs: [
      {
        question: 'Do foreign nationals need a U.S. Social Security number to get a mortgage?',
        answer: 'Not always. Some lenders offer foreign national programs that work with a passport, visa, and foreign credit documentation in place of a Social Security number. Requirements vary by lender and loan program.',
      },
      {
        question: 'Can a foreign national purchase an investment property in the U.S.?',
        answer: 'Yes. Many foreign national programs are designed specifically for investment properties, including single-family rentals, condominiums, and multi-unit residences. Underwriting typically focuses on the property\'s income potential and the borrower\'s overall financial profile.',
      },
      {
        question: 'What down payment is typically required for a foreign national loan?',
        answer: 'Down payment requirements vary, but many foreign national programs require 25% to 35% down. The higher equity requirement reflects the additional complexity of verifying foreign income and credit.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'U.S. citizenship is not a prerequisite for purchasing American real estate. Foreign nationals — including non-resident aliens, visa holders, and individuals with no U.S. credit history — may be eligible to buy property in the United States through specialized lending programs designed for exactly this situation.' },
      { type: 'heading', text: 'Who Typically Uses Foreign National Financing' },
      { type: 'list', items: [
        'International buyers purchasing a second home or vacation property in the U.S.',
        'Parents purchasing a residence for a child attending a U.S. university.',
        'International investors seeking to diversify through U.S. real estate.',
        'Business owners who spend significant time in the U.S. and want a fixed base.',
        'Individuals building wealth in a stable, familiar market.',
      ]},
      { type: 'heading', text: 'What Lenders Typically Review' },
      { type: 'paragraph', text: 'Because foreign national borrowers fall outside conventional U.S. underwriting frameworks, lenders evaluate these loans differently. Documentation typically includes a valid passport, visa (if applicable), foreign credit references or letters from international banks, bank statements demonstrating assets and income, and information about the subject property. Reserves — cash held after closing — are often a meaningful part of the qualifying picture.' },
      { type: 'callout', text: 'Foreign national programs vary significantly from lender to lender. What one institution cannot accommodate, another may handle comfortably. Working with an advisor who understands this landscape is often the difference between a yes and a no.' },
      { type: 'heading', text: 'Property Types and Use Cases' },
      { type: 'paragraph', text: 'Foreign national loans are available for primary residences, second homes, and investment properties, though eligibility and terms vary by use. Some programs are specifically structured around investment properties and evaluate the rental income potential of the subject property as part of the qualifying analysis.' },
      { type: 'heading', text: 'A Note on Legal and Tax Considerations' },
      { type: 'paragraph', text: 'This article addresses the mortgage financing component of foreign national property ownership only. Purchasing U.S. real estate as a non-resident may carry distinct tax, legal, and reporting obligations depending on your country of residence, visa status, and ownership structure. Consulting with a U.S. tax advisor and attorney familiar with international transactions is recommended before proceeding.' },
      { type: 'quote', text: 'The financing exists. The real question is understanding what documentation tells the clearest story about who you are as a borrower — and finding the lender who knows how to read it.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'heloc-vs-heloan',
    title: 'HELOC vs. HELOAN: What\'s the Difference?',
    excerpt: 'A HELOC gives you revolving access to your equity. A HELOAN gives you a lump sum. Understanding the distinction helps you choose the right structure for your goals.',
    categories: ['HELOC', 'HELOAN'],
    gradient: 'linear-gradient(135deg, #c4ccd0 0%, #6e8a94 100%)',
    image: '/images/resources-11.png',
    readTime: '5 min read',
    date: 'May 28, 2026',
    featured: false,
    relatedSlugs: ['heloc-vs-cash-out-refinance', 'buying-before-selling', 'fha-vs-conventional'],
    faqs: [
      {
        question: 'Can I have both a HELOC and a HELOAN at the same time?',
        answer: 'In some cases, yes — depending on your available equity and the lender\'s guidelines. Both products sit in a second lien position behind your primary mortgage and are subject to combined loan-to-value limits.',
      },
      {
        question: 'Does a HELOAN have a fixed interest rate?',
        answer: 'Most HELOANs carry fixed interest rates, which means your payment remains the same for the life of the loan. This predictability is one of the main reasons borrowers choose a HELOAN over a HELOC.',
      },
      {
        question: 'Will a HELOC or HELOAN affect my first mortgage?',
        answer: 'Neither product replaces or modifies your existing first mortgage. They are separate loans secured by your home\'s equity. This is an important distinction if your current first mortgage carries a favorable rate you want to protect.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'Both a HELOC and a HELOAN let you access the equity you\'ve built in your home — but they work differently, carry different structures, and suit different purposes. Choosing between them starts with understanding what you\'re actually trying to accomplish.' },
      { type: 'heading', text: 'The HELOC: Revolving Access to Equity' },
      { type: 'paragraph', text: 'A Home Equity Line of Credit works more like a credit card than a traditional loan. You\'re approved for a maximum credit limit based on your available equity, and you draw from that line as needed during the draw period — typically 10 years. You pay interest only on the amount drawn, not the total line. After the draw period closes, the loan enters repayment.' },
      { type: 'paragraph', text: 'HELOCs are commonly structured with variable interest rates, meaning your rate — and therefore your payment — can fluctuate over time. Fixed-rate HELOC options may also be available through some lenders.' },
      { type: 'heading', text: 'The HELOAN: A Lump Sum with Fixed Terms' },
      { type: 'paragraph', text: 'A Home Equity Loan — often called a HELOAN or a second mortgage — provides a single disbursement at closing. You receive the full amount upfront and repay it over a fixed term with a fixed interest rate. Your payment stays consistent from month one through the final payment.' },
      { type: 'callout', text: 'If you know exactly how much you need and want payment certainty, a HELOAN often makes more sense. If your needs are ongoing or uncertain in scope, a HELOC\'s revolving access offers more flexibility.' },
      { type: 'heading', text: 'When Each Makes Sense' },
      { type: 'list', items: [
        'HELOC: Ongoing home renovation with costs spread across multiple phases.',
        'HELOC: A financial reserve you\'d like access to but may not fully use.',
        'HELOC: Business expenses or tuition with uncertain timing.',
        'HELOAN: Debt consolidation where you know the exact amount.',
        'HELOAN: A single large project — roof replacement, addition, or major renovation.',
        'HELOAN: Borrowers who want predictable, fixed monthly payments.',
      ]},
      { type: 'heading', text: 'A Note on Your First Mortgage Rate' },
      { type: 'paragraph', text: 'One advantage both HELOCs and HELOANs share over a cash-out refinance is that they leave your first mortgage untouched. If you secured your current first mortgage at a favorable rate, accessing equity through a second lien product allows you to preserve that rate rather than replacing it with a new loan at current market pricing.' },
      { type: 'quote', text: 'The decision between a HELOC and a HELOAN isn\'t just about rates. It\'s about how you want to access your equity, how much certainty you need in your payment, and how much flexibility your situation actually requires.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'should-you-put-20-percent-down',
    title: 'Should You Put 20% Down? Not Always.',
    excerpt: 'Twenty percent down avoids mortgage insurance and reduces your loan balance — but it isn\'t always the smartest use of your capital. Here\'s how to think through the decision.',
    categories: ['Conventional'],
    gradient: 'linear-gradient(135deg, #d0cac0 0%, #a09080 100%)',
    image: '/images/resources-12.png',
    readTime: '6 min read',
    date: 'May 20, 2026',
    featured: false,
    relatedSlugs: ['fha-vs-conventional', 'jumbo-loan-requirements', 'heloc-vs-cash-out-refinance'],
    faqs: [
      {
        question: 'What is mortgage insurance and when is it required?',
        answer: 'Mortgage insurance — often called PMI on conventional loans — is typically required when a borrower puts less than 20% down. It protects the lender, not the borrower, and adds to the monthly payment. On conventional loans, PMI can be removed once the loan balance reaches 80% of the original home value.',
      },
      {
        question: 'Is it ever better to put less than 20% down?',
        answer: 'Yes. If the cost of PMI is relatively low and preserving cash allows you to maintain reserves, fund renovations, or deploy capital elsewhere productively, a smaller down payment may be the better financial decision. The math depends on your specific situation.',
      },
      {
        question: 'Can I avoid PMI without putting 20% down?',
        answer: 'In some cases. Options include lender-paid mortgage insurance (LPMI), where the cost is built into a slightly higher rate, or an 80/10/10 structure (a first mortgage at 80%, a second lien at 10%, and 10% down). Both have tradeoffs worth evaluating.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'The 20% down rule is one of the most widely repeated pieces of home buying advice — and one of the most misunderstood. It has a real logic behind it: avoiding mortgage insurance, reducing your loan balance, and entering the transaction with meaningful equity. But it isn\'t the universal right answer. For many buyers, putting 20% down is the most expensive decision they make.' },
      { type: 'heading', text: 'What 20% Down Actually Does' },
      { type: 'paragraph', text: 'On a conventional loan, a 20% down payment eliminates the need for private mortgage insurance (PMI), which typically runs between 0.5% and 1.5% of the loan amount annually. It also reduces the loan balance, which lowers your monthly payment and the total interest paid over the life of the loan. These are real benefits — but they come at a cost: a significant reduction in your liquid capital.' },
      { type: 'heading', text: 'The Opportunity Cost of Tying Up Capital' },
      { type: 'paragraph', text: 'Money placed into a down payment is no longer available for anything else. For buyers who are stretching to reach 20%, that can mean depleted emergency funds, no budget for immediate repairs or renovations, and reduced financial flexibility in the months after closing. The question isn\'t whether 20% down is better in isolation — it\'s whether it\'s better given everything else competing for that capital.' },
      { type: 'callout', text: 'Running out of liquidity after closing is a more common problem than most buyers anticipate. A home requires ongoing capital — for maintenance, for the unexpected, for making it your own. Arriving at closing with reserves intact is worth something.' },
      { type: 'heading', text: 'Comparing Down Payment Options' },
      { type: 'list', items: [
        '3–5% down: Maximizes liquidity, carries PMI, higher monthly payment. Can make sense when preserving capital is the priority.',
        '10% down: A middle path — reduces PMI cost and loan size while retaining meaningful reserves.',
        '15% down: Gets closer to eliminating PMI while preserving some flexibility.',
        '20% down: Eliminates PMI and secures the most competitive pricing. Best when capital is not constrained.',
        'Above 20%: Reduces loan size further and may improve pricing on jumbo loans, but diminishing returns on liquidity tradeoff.',
      ]},
      { type: 'heading', text: 'When 20% Down Makes Clear Sense' },
      { type: 'paragraph', text: 'If you have the capital available, strong reserves that won\'t be depleted, no immediate renovation needs, and no competing investment priorities, 20% down is a sound choice. It simplifies the loan, eliminates ongoing PMI costs, and reduces long-term interest. The decision is straightforward when capital is not the constraint.' },
      { type: 'heading', text: 'When a Smaller Down Payment May Be Smarter' },
      { type: 'paragraph', text: 'If reaching 20% would leave you with little reserve, forgo a needed renovation, or require passing on a more productive use of capital, a smaller down payment may serve you better — even accounting for PMI. The cost of PMI, while real, is often lower than the cost of financial stress or missed opportunity.' },
      { type: 'quote', text: 'The best down payment is the one that gets you into the right home, keeps you financially stable, and leaves you positioned to manage what comes next. That number is different for everyone.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
    ],
  },
  {
    slug: 'physician-loans-doctors-buying-home',
    title: 'Physician Loans: What Doctors Should Know About Buying a Home',
    excerpt: 'Physician mortgage programs are designed for medical professionals with strong future income but limited savings after years of training. Here\'s how they work and when they may make sense.',
    categories: ['Professionals'],
    gradient: 'linear-gradient(135deg, #c8cfc8 0%, #7a8c7a 100%)',
    image: '/images/resources-13.png',
    readTime: '7 min read',
    date: 'June 21, 2026',
    featured: false,
    relatedSlugs: ['should-you-put-20-percent-down', 'jumbo-loan-requirements', 'bank-statement-loans'],
    faqs: [
      {
        question: 'Can I use a physician loan if I haven\'t started my new position yet?',
        answer: 'In many cases, yes. Some physician loan programs will accept a fully executed offer letter in place of pay stubs, provided the start date falls within a defined window — often 150 days from the note date. Documentation requirements vary by lender and should be confirmed during the application process.',
      },
      {
        question: 'Are student loans counted against me in physician loan underwriting?',
        answer: 'Student loans in deferment may be excluded from the debt-to-income calculation under some physician loan programs, subject to the lender\'s specific guidelines and borrower profile. This is one of the meaningful distinctions between physician loans and conventional mortgage underwriting.',
      },
      {
        question: 'Do physician loans require mortgage insurance?',
        answer: 'Many physician loan programs do not require private mortgage insurance (PMI), even when financing above 80% of the purchase price. This is one of the defining features of the product — allowing higher loan-to-value financing without the additional monthly cost of PMI.',
      },
      {
        question: 'Which degrees are typically eligible for physician loan programs?',
        answer: 'Eligible designations vary by lender, but commonly include MD, DO, DDS, DMD, PharmD, VMD, DVM, DPM, and CRNA with a DNP or DNAP. Some programs extend to additional healthcare professionals. Eligibility should be confirmed with the lender.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'Physicians are often in a financially unusual position: highly trained, high earning potential, and yet — particularly early in their careers — limited in the savings and credit history that traditional mortgage underwriting rewards. Years of medical school and residency are not years of wealth accumulation. They are years of deferred income, student debt, and long hours.' },
      { type: 'paragraph', text: 'Physician mortgage programs were developed to address that gap. They recognize the trajectory rather than just the present-day balance sheet, and in doing so, they can open the door to homeownership at a stage of a medical professional\'s career when conventional financing may present real obstacles.' },
      { type: 'heading', text: 'What Is a Physician Loan?' },
      { type: 'paragraph', text: 'A physician loan — sometimes called a doctor mortgage or medical professional loan — is a specialized residential lending product offered by select lenders to qualifying medical professionals. These programs typically allow higher loan amounts, lower or no down payment requirements, no private mortgage insurance, and more flexible income documentation than conventional loan programs.' },
      { type: 'paragraph', text: 'They are not government-backed programs. They are portfolio products offered by individual lenders, which means terms, eligibility, and guidelines vary meaningfully from one institution to another.' },
      { type: 'heading', text: 'Why Physician Loans Exist' },
      { type: 'paragraph', text: 'A physician finishing a residency and entering an attending role might be stepping into a salary of $250,000 or more — but they may also carry $200,000 to $400,000 in student debt accumulated over a decade of training. Under traditional mortgage underwriting, that debt-to-income ratio would disqualify many applicants regardless of income trajectory.' },
      { type: 'paragraph', text: 'Physician loan programs account for the professional context. They recognize that a licensed physician with a signed employment contract is not the same credit risk as a borrower with equivalent debt and uncertain income. The product exists because the standard model does not fit the situation.' },
      { type: 'heading', text: 'Who May Qualify?' },
      { type: 'paragraph', text: 'Eligible degrees commonly include MD, DO, DDS, DMD, PharmD, VMD, DVM, DPM, and CRNA with a DNP or DNAP, though programs vary. First-time homebuyers are typically eligible. A minimum credit score of 680 is common, though higher scores may unlock better pricing or expanded options.' },
      { type: 'callout', text: 'Eligibility, loan limits, documentation requirements, and program terms vary by lender, borrower profile, property type, and current guidelines. What\'s available through one lender may differ significantly from another. Speaking with a mortgage advisor who understands the landscape is the most reliable starting point.' },
      { type: 'heading', text: 'Key Benefits' },
      { type: 'list', items: [
        'Financing up to 100% of the purchase price, potentially eliminating the need for a down payment.',
        'Loan amounts that may reach up to $2,000,000, accommodating higher-cost markets.',
        'No private mortgage insurance (PMI), even with minimal down payment.',
        'Non-occupant co-borrowers may be permitted, with income contribution limits that vary by program.',
        'Escrow accounts for taxes and insurance are typically required.',
      ]},
      { type: 'heading', text: 'Income and Offer Letter Flexibility' },
      { type: 'paragraph', text: 'One of the more practical advantages of physician loan programs is how they handle employment documentation. A physician completing training and beginning a new attending position may not have months of pay stubs to present at closing. Some programs will accept a fully executed offer letter in lieu of pay stubs, provided the start date is within approximately 150 days of the note date.' },
      { type: 'paragraph', text: 'Consider a scenario: a physician finishing her final year of residency accepts a position at a hospital system starting in two months. She wants to purchase a home near her new hospital before her start date. A conventional lender would typically require two years of tax returns and current pay stubs — documentation she cannot provide. A physician loan program may allow her to proceed using her executed offer letter, credential verification, and current residency income.' },
      { type: 'paragraph', text: 'For 1099 or contract employees, some programs will consider income from an executed contract that specifies a guaranteed salary or hourly rate. Requirements vary and should be reviewed carefully with the lender.' },
      { type: 'heading', text: 'Student Loans and DTI' },
      { type: 'paragraph', text: 'Student loan debt is often the single largest obstacle physicians face in conventional mortgage qualification. Under standard underwriting, even deferred student loans are factored into the debt-to-income ratio — often at a calculated payment that can significantly affect the qualifying picture.' },
      { type: 'paragraph', text: 'Some physician loan programs may exclude student loans that are in deferment from the DTI calculation, subject to the program\'s specific guidelines. This distinction can be meaningful for borrowers carrying significant educational debt who would otherwise qualify comfortably on income alone.' },
      { type: 'heading', text: 'What to Watch For' },
      { type: 'paragraph', text: 'The flexibility of physician loans comes with considerations worth understanding. Financing 100% of a purchase price means entering the transaction with no equity cushion. Interest rates on physician programs may differ from conventional rates. And because these are portfolio products — not standardized government-backed loans — terms can change, and not every lender offers them.' },
      { type: 'paragraph', text: 'Preserving liquidity is a legitimate reason to minimize a down payment. But borrowers should still think carefully about reserve levels, monthly payment comfort, and the financial demands of homeownership in the early months.' },
      { type: 'heading', text: 'When a Physician Loan May Make Sense' },
      { type: 'list', items: [
        'You are beginning a new attending or associate position and cannot yet document income through traditional pay stubs.',
        'You carry significant student debt that would affect your DTI under conventional underwriting.',
        'You want to preserve cash reserves for moving costs, home furnishings, or unexpected repairs.',
        'You are purchasing in a market where a 20% down payment would represent a significant portion of your available capital.',
        'You want to avoid PMI without putting 20% down.',
      ]},
      { type: 'heading', text: 'When It May Not Be the Best Fit' },
      { type: 'paragraph', text: 'If you have sufficient savings for a meaningful down payment, a conventional mortgage may offer more competitive pricing. If your income is well-documented and your student debt load is manageable within standard DTI limits, the specialized features of a physician program may not be necessary. The right loan is always the one that fits your actual situation — not the one with the most compelling features on paper.' },
      { type: 'quote', text: 'A physician loan is a tool, not a default. For the right borrower at the right moment, it removes barriers that would otherwise delay homeownership without good reason. For others, a conventional mortgage may simply be the better deal.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
      { type: 'callout', text: 'Program availability, eligibility, rates, loan limits, DTI treatment, reserve requirements, and documentation standards vary by lender, borrower profile, property type, and current guidelines. This article is for educational purposes only and does not constitute a loan commitment or guarantee of financing.' },
    ],
  },
  {
    slug: 'fix-and-flip-loans-real-estate-investors',
    title: 'Fix & Flip Loans: Financing Solutions for Real Estate Investors',
    excerpt: 'Fix and flip financing is built for speed, flexibility, and leverage — but successful projects begin long before the first offer. Here\'s what investors should understand.',
    categories: ['Fix & Flip', 'Hard Money'],
    gradient: 'linear-gradient(135deg, #c4bdb4 0%, #8c7d6e 100%)',
    image: '/images/resources-14.png',
    readTime: '6 min read',
    date: 'June 21, 2026',
    featured: false,
    relatedSlugs: ['what-is-a-hard-money-loan', 'dscr-loans-explained', 'buying-before-selling'],
    faqs: [
      {
        question: 'Can I finance both the purchase and renovation with a fix and flip loan?',
        answer: 'Many fix and flip loan programs are structured to cover both the acquisition cost and a portion of the renovation budget, sometimes referred to as a rehab holdback. Renovation funds are typically disbursed in draws as work is completed and inspected, rather than provided in a lump sum at closing.',
      },
      {
        question: 'How quickly can a fix and flip loan close?',
        answer: 'Speed is one of the defining advantages of fix and flip financing. Depending on the lender and the complexity of the deal, closings can occur in as few as 7 to 14 days — significantly faster than conventional mortgage timelines. This matters in competitive markets where speed can determine whether you secure a property.',
      },
      {
        question: 'What happens if my renovation takes longer than expected?',
        answer: 'Most fix and flip loans are short-term — typically 6 to 18 months. If a project runs over timeline, some lenders will offer extensions, though additional fees may apply. Accurate renovation budgeting and timeline planning before closing is essential to avoiding this situation.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'Fix and flip investing is often portrayed as a straightforward formula: buy low, renovate, sell high. In practice, the financing component alone requires careful thought. The wrong loan structure, a miscalculated renovation budget, or an unrealistic exit timeline can turn a promising project into a costly one.' },
      { type: 'paragraph', text: 'Fix and flip loans are short-term financing products designed specifically for investors purchasing properties with the intent to renovate and resell. They are not traditional mortgages. They behave more like bridge loans — built for speed, asset-based, and structured around a defined timeline and exit.' },
      { type: 'heading', text: 'How Fix & Flip Financing Differs from a Traditional Mortgage' },
      { type: 'paragraph', text: 'A conventional mortgage underwrites the borrower — your income, credit history, and debt-to-income ratio. A fix and flip loan underwrites the deal. Lenders focus primarily on the after-repair value (ARV) of the property, the scope and cost of the renovation, the borrower\'s experience, and the viability of the exit strategy. Personal income documentation is typically less central to the approval.' },
      { type: 'paragraph', text: 'This distinction allows investors to move quickly and finance properties that would not qualify for conventional financing — distressed homes, properties with deferred maintenance, or acquisitions requiring speed that a traditional lender cannot provide.' },
      { type: 'heading', text: 'Typical Loan Terms' },
      { type: 'list', items: [
        'Loan terms ranging from 6 to 18 months, with some programs extending to 24 months.',
        'Interest rates higher than conventional mortgages, reflecting the short-term, flexible nature of the product.',
        'Loan-to-value and loan-to-cost ratios vary by lender, borrower experience, and property type.',
        'Points and origination fees are common — these should be factored into the total project cost.',
        'Draw schedules for renovation funds, tied to inspection milestones.',
      ]},
      { type: 'heading', text: 'Purchase Plus Renovation Financing' },
      { type: 'paragraph', text: 'Many fix and flip programs allow borrowers to finance both the acquisition and the renovation in a single loan. The renovation portion is typically held back and disbursed in draws as work is completed and verified. This structure allows investors to leverage their capital across multiple projects rather than tying up large reserves in a single renovation.' },
      { type: 'callout', text: 'Renovation budgets should be stress-tested before closing. Cost overruns and unexpected structural issues are common, and the timeline for a sale is not guaranteed. Investors who plan only for best-case scenarios tend to encounter the most problems.' },
      { type: 'heading', text: 'Exit Strategy Is Not Optional' },
      { type: 'paragraph', text: 'Every fix and flip loan has a maturity date. When that date arrives, the loan must be repaid — either through the sale of the property, a refinance into longer-term financing, or another liquidity event. Investors who enter a project without a clear and realistic exit strategy are borrowing against a plan they don\'t have.' },
      { type: 'paragraph', text: 'Consider a scenario: an investor purchases a distressed single-family home at a discount with a 12-month fix and flip loan. The renovation runs two months over schedule due to permitting delays. The market softens slightly, and the expected sales price drops. Without adequate reserves and a defined backup plan, the investor is now under pressure as the loan maturity approaches. The margin that looked comfortable at the start has compressed.' },
      { type: 'heading', text: 'Common Investor Mistakes' },
      { type: 'list', items: [
        'Underestimating renovation costs, particularly for older properties or structural work.',
        'Overestimating the after-repair value based on optimistic comparables.',
        'Failing to account for holding costs — interest, taxes, insurance, and utilities during the renovation period.',
        'Ignoring local market conditions and how quickly properties at the target price point are actually selling.',
        'Entering a project without a contingency reserve for unexpected costs.',
      ]},
      { type: 'heading', text: 'When Fix & Flip Financing May Make Sense' },
      { type: 'paragraph', text: 'Fix and flip financing is a useful tool for experienced investors who can accurately estimate renovation costs, move quickly on acquisitions, and manage the full project cycle from purchase through sale. It can also work for first-time investors who take a conservative approach — modest scope, realistic timelines, and well-understood exit.' },
      { type: 'quote', text: 'The investors who do this well are the ones who respect the math before they fall in love with the property. The numbers have to work at purchase — not just at the hoped-for sale price.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
      { type: 'callout', text: 'Program availability, loan terms, rates, LTV limits, draw schedules, and documentation requirements vary by lender, borrower experience, property type, and market. This article is for educational purposes only and does not constitute a loan commitment or guarantee of financing.' },
    ],
  },
  {
    slug: 'dscr-loans-multi-family-rental-properties',
    title: 'DSCR Loans for Multi-Family and Rental Properties',
    excerpt: 'DSCR loans let investors qualify based on a property\'s rental income rather than personal income. Here\'s how they work and when they may be the right fit.',
    categories: ['DSCR'],
    gradient: 'linear-gradient(135deg, #c0c8c4 0%, #6e8a82 100%)',
    image: '/images/resources-15.png',
    readTime: '6 min read',
    date: 'June 21, 2026',
    featured: false,
    relatedSlugs: ['dscr-loans-explained', 'fix-and-flip-loans-real-estate-investors', 'jumbo-loan-requirements'],
    faqs: [
      {
        question: 'What DSCR ratio do most lenders require?',
        answer: 'Many lenders require a minimum DSCR of 1.0 to 1.25, though requirements vary. A DSCR of 1.0 means the property generates exactly enough income to cover the loan payment. A ratio above 1.25 indicates a more comfortable buffer. Some programs allow ratios below 1.0 with compensating factors such as strong reserves or a larger down payment.',
      },
      {
        question: 'Can I use projected rental income to qualify for a DSCR loan?',
        answer: 'On properties that are vacant or newly acquired, lenders typically rely on a market rent analysis — often from an appraisal — to estimate rental income. On occupied properties with existing leases, the actual lease income is typically used. Documentation requirements vary by lender and property type.',
      },
      {
        question: 'Are DSCR loans available for multi-family properties?',
        answer: 'Yes. DSCR financing is commonly used for both single-family rental properties and small to mid-size multi-family properties. Loan structure, reserve requirements, and documentation can differ between property types and should be reviewed with a lender familiar with investment property financing.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'For investors building a rental portfolio, one of the most significant obstacles to growth is the traditional income verification process. Conventional mortgage underwriting is designed for owner-occupied buyers with W-2 income — not for investors whose earnings may be complex, variable, or reported in ways that don\'t translate cleanly to a tax return.' },
      { type: 'paragraph', text: 'DSCR loans offer a different qualifying framework. Rather than evaluating the borrower\'s personal income, debt, and tax documents in depth, these programs focus primarily on the income generated by the investment property itself — and whether that income is sufficient to service the debt.' },
      { type: 'heading', text: 'What Is a DSCR Ratio?' },
      { type: 'paragraph', text: 'DSCR stands for Debt Service Coverage Ratio. It is calculated by dividing the gross rental income of the property by the total monthly loan payment — principal, interest, taxes, insurance, and any HOA fees. A DSCR of 1.25 means the property generates 25% more income than is needed to cover the payment. A ratio of 1.0 means income exactly equals the payment. Below 1.0 means the property does not fully cover its own debt service.' },
      { type: 'callout', text: 'A higher DSCR generally reflects a more conservative investment — more income cushion above the loan payment. Lenders view this favorably, and it often translates to better pricing or expanded loan options.' },
      { type: 'heading', text: 'How Rental Income Is Evaluated' },
      { type: 'paragraph', text: 'For properties with existing leases, most lenders use the current lease income as the qualifying rent. For vacant properties or acquisitions without in-place leases, lenders typically rely on a market rent schedule from the property\'s appraisal. Self-reported rental income estimates are generally not sufficient without supporting documentation.' },
      { type: 'heading', text: 'Single-Family vs. Multi-Family Investments' },
      { type: 'paragraph', text: 'DSCR financing is available for both single-family rental properties and small multi-family buildings, typically up to four or eight units depending on the program. Multi-family properties often benefit from diversified income — multiple rent-paying units reduce the impact of a single vacancy. However, multi-family underwriting may involve different reserve requirements, documentation, and LTV limits than single-family rentals.' },
      { type: 'heading', text: 'Advantages for Investors' },
      { type: 'list', items: [
        'No personal income documentation required in many cases — no tax returns, no W-2s, no pay stubs.',
        'Qualification based on property performance rather than personal DTI.',
        'Ability to scale a portfolio without each new acquisition being limited by the borrower\'s personal income capacity.',
        'Available to self-employed investors, business owners, and high-net-worth individuals with complex income structures.',
        'Often compatible with LLC or entity ownership structures, depending on the program.',
      ]},
      { type: 'heading', text: 'Scaling a Rental Portfolio' },
      { type: 'paragraph', text: 'One of the most practical advantages of DSCR financing for investors is the ability to grow a portfolio without each new acquisition triggering a full personal income review. Because the loan qualifies on the property, an investor with ten existing rentals is not necessarily at a disadvantage compared to one with two — as long as each property can demonstrate sufficient cash flow.' },
      { type: 'paragraph', text: 'Consider a scenario: a self-employed investor owns three single-family rentals, all financed through DSCR loans. His tax returns show modest net income after deductions — a profile that conventional underwriting would struggle to accommodate. He identifies a four-unit property with strong in-place rents and a DSCR above 1.25. The DSCR program allows him to acquire the property based on the rental income, without his personal tax returns becoming the primary limiting factor.' },
      { type: 'heading', text: 'Common Misconceptions' },
      { type: 'list', items: [
        'DSCR loans are not income-free approvals. Credit, reserves, property condition, and overall financial profile still matter.',
        'A positive DSCR does not guarantee approval — lenders evaluate the full picture.',
        'Not all DSCR programs allow below-1.0 ratios. Those that do typically require additional compensating factors.',
        'Market rent used for vacant properties is an estimate, not a guarantee of actual income.',
      ]},
      { type: 'quote', text: 'DSCR financing doesn\'t remove risk from real estate investing — it removes a structural barrier that prevents otherwise qualified investors from accessing capital. The investment still has to make sense.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
      { type: 'callout', text: 'Program availability, DSCR thresholds, LTV limits, reserve requirements, eligible property types, and documentation standards vary by lender, borrower profile, and current guidelines. This article is for educational purposes only and does not constitute a loan commitment or guarantee of financing.' },
    ],
  },
  {
    slug: 'financing-airbnb-short-term-rental-properties',
    title: 'Financing for Airbnb and Short-Term Rental Properties',
    excerpt: 'Short-term rentals present real investment opportunity — and real complexity. Here\'s how financing works and what investors should consider before acquiring an Airbnb property.',
    categories: ['DSCR'],
    gradient: 'linear-gradient(135deg, #c8c4bc 0%, #908070 100%)',
    image: '/images/resources-16.png',
    readTime: '6 min read',
    date: 'June 21, 2026',
    featured: false,
    relatedSlugs: ['dscr-loans-multi-family-rental-properties', 'dscr-loans-explained', 'fix-and-flip-loans-real-estate-investors'],
    faqs: [
      {
        question: 'Can Airbnb income be used to qualify for a mortgage?',
        answer: 'Some lenders offer programs that evaluate short-term rental income as part of the qualifying analysis, often using market rent data or STR income history. Requirements vary significantly by lender and program. Many conventional loan programs do not recognize short-term rental income the same way as long-term leases.',
      },
      {
        question: 'Is a DSCR loan available for Airbnb properties?',
        answer: 'Some DSCR programs accommodate short-term rentals, using either actual STR income history or a market-based analysis to determine qualifying income. Not all DSCR lenders accept short-term rental properties — working with a lender experienced in this product type is important.',
      },
      {
        question: 'What are the biggest risks of short-term rental investing?',
        answer: 'The most significant risks include seasonality and income variability, changing local regulations that restrict or prohibit short-term rentals, high operating expenses relative to long-term rentals, and the management intensity of the business. Financing a property that depends on consistent Airbnb occupancy to cover its debt service carries meaningful exposure to all of these factors.',
      },
    ],
    body: [
      { type: 'paragraph', text: 'Short-term rental investing — properties listed on Airbnb, Vrbo, and similar platforms — has grown significantly as a real estate strategy. The appeal is understandable: well-located properties in the right markets can generate substantially more income per night than a comparable long-term lease. But the financing, the operations, and the risk profile are meaningfully different from traditional rental investing. Understanding those differences matters before the first offer is written.' },
      { type: 'heading', text: 'Can Airbnb Income Be Used to Qualify?' },
      { type: 'paragraph', text: 'This is the first question most investors ask — and the answer depends on the loan program and the lender. Conventional mortgage programs backed by Fannie Mae and Freddie Mac have specific rules around how rental income is documented and counted, and short-term rental income does not always fit neatly within those frameworks.' },
      { type: 'paragraph', text: 'Some non-QM and DSCR programs take a different approach, allowing lenders to underwrite based on the property\'s short-term rental income history or projected market income. These programs exist, but they are not universal, and the requirements for how income is documented vary widely.' },
      { type: 'heading', text: 'DSCR Financing for Short-Term Rentals' },
      { type: 'paragraph', text: 'For investors who cannot or choose not to document personal income, DSCR loans are often the most practical financing option for short-term rental properties. The loan qualifies based on the property\'s income rather than the borrower\'s personal financial profile — which aligns naturally with how many STR investors think about their investments.' },
      { type: 'paragraph', text: 'Some DSCR lenders will use actual Airbnb income history from platforms or tax documents. Others rely on a market rent analysis that estimates what the property would generate as a long-term rental, using that as a more conservative proxy. Investors with a strong income history through a platform may qualify for better terms than those purchasing a property without an established track record.' },
      { type: 'callout', text: 'If a property\'s DSCR calculation is based on short-term rental projections, investors should stress-test the scenario at long-term rental income levels. If the property cash flows at long-term rates, the investment has a meaningful safety margin. If it only works at peak STR occupancy, the risk profile changes.' },
      { type: 'heading', text: 'Long-Term vs. Short-Term Rental Analysis' },
      { type: 'paragraph', text: 'One of the most important decisions in STR investing is whether the income premium over long-term renting is large enough to justify the added complexity, costs, and risk. Short-term rentals carry higher operating expenses — cleaning, furnishing, platform fees, utilities, and management. They are also more sensitive to seasonality, market saturation, and platform algorithm changes. In many markets, a well-located property can earn two to three times the long-term rent on a nightly basis. In others, the premium is modest once operating costs are accounted for.' },
      { type: 'heading', text: 'Local Regulations and Licensing' },
      { type: 'paragraph', text: 'This is the risk that surprises investors most often. Short-term rental regulations vary dramatically by city, county, and even neighborhood. Some jurisdictions require permits or licenses, cap the number of rental days per year, require owner-occupancy, or restrict STRs to certain zones. Others have moved to ban them outright or limit new permits.' },
      { type: 'paragraph', text: 'An investor who finances a property based on projected Airbnb income and then encounters a local ordinance limiting rental nights or requiring a license that isn\'t available faces a significant problem. Researching local STR regulations before purchase — not after — is not optional.' },
      { type: 'heading', text: 'A Real-World Scenario' },
      { type: 'paragraph', text: 'Consider an investor who purchases a two-bedroom condominium in a coastal market with the intent to operate it as a short-term rental. She finances it using a DSCR loan, with the qualifying income based on the property\'s projected STR income. In her first year, occupancy is strong during summer but drops significantly in the off-season. Operating costs — cleaning fees, HOA, insurance, utilities, and platform fees — run higher than projected. The property is profitable, but more narrowly than her initial model suggested. In year two, the municipality introduces a new short-term rental licensing cap. She is grandfathered in under existing rules, but new permits are no longer being issued — which affects the property\'s future resale value to investors intending to operate it the same way.' },
      { type: 'heading', text: 'Investment Risks Worth Naming' },
      { type: 'list', items: [
        'Income is variable and dependent on occupancy, seasonality, and platform performance.',
        'Operating expenses are meaningfully higher than long-term rentals.',
        'Regulatory risk is real and can change the investment profile after purchase.',
        'Management intensity is significant — STR is a business, not a passive income source.',
        'Financing options are more limited than for long-term rentals, and lender requirements vary considerably.',
      ]},
      { type: 'quote', text: 'Short-term rentals can be strong investments. They can also be deeply complicated ones. The difference usually comes down to how carefully the investor understood the market, the regulations, and the actual costs before committing to the property.', attribution: 'Jennifer Ko, Founder of Koast Capital' },
      { type: 'callout', text: 'Financing availability, qualifying income treatment, DSCR thresholds, down payment requirements, and eligible property types vary by lender, program, borrower profile, and current guidelines. Local short-term rental regulations are subject to change and should be independently verified before purchase. This article is for educational purposes only and does not constitute a loan commitment or guarantee of financing.' },
    ],
  },
]

export default articles

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug)
}

export function getRelatedArticles(slugs: string[]): Article[] {
  return slugs
    .map((s) => articles.find((a) => a.slug === s))
    .filter(Boolean) as Article[]
}
